import {Buildings} from "@/src/const/techTree";

export const popularCivs = [
    "Mongols",
    "Franks",
    "Magyars",
    "Persians",
    "Khmer",
    "Spanish",
    "Huns",
    "Britons",
    "Ethiopians",
    "Lithuanians",
    "Teutons",
    "Byzantines",
    "Hindustanis",
    "Turks",
    "Vietnamese",
    "Cumans",
    "Portuguese",
    "Goths",
    "Mayans",
    "Chinese",
    "Saracens",
    "Georgians",
    "Celts",
    "Berbers",
    "Bohemians",
    "Poles",
    "Sicilians",
    "Burgundians",
    "Malay",
    "Malians",
    "Bulgarians",
    "Japanese",
    "Tatars",
    "Incas",
    "Vikings",
    "Aztecs",
    "Slavs",
    "Italians",
    "Koreans",
    "Romans",
    "Gurjaras",
    "Armenians",
    "Burmese",
    "Bengalis",
    "Dravidians"
];

export const BuildingsForTreeQ = [
    Buildings.Barracks,
    Buildings.ArcheryRange,
    Buildings.Stable,
    Buildings.Blacksmith,
    Buildings.Monastery,
    Buildings.SiegeWorkshop,
]
